= Appointment
API Endpoint to manage Tandemmasters


== Create/Add Tandemmaster
A `POST` request is used to add a new tandemmaster.

operation::tandemmaster/create-tandemmaster[snippets='http-request,request-fields,http-response,response-fields']


== Get all Tandemmasters
A `GET` request is used to get all tandemmasters.

operation::tandemmaster/get-tandemmasters[snippets='http-request,http-response,response-fields']


== Get Tandemmaster
A `GET` request is used to get one tandemmaster.

operation::tandemmaster/get-tandemmaster[snippets='http-request,path-parameters,http-response,response-fields']


== Get Me Tandemmaster
A `GET` request is used by a tandemmaster to get his own data

operation::tandemmaster/get-me-tandemmasters[snippets='http-request,path-parameters,http-response,response-fields']


== Update Tandemmaster
A `PUT` request is used to update a tandemmaster.

operation::tandemmaster/update-tandemmaster[snippets='http-request,path-parameters,request-fields,http-response,response-fields']


== Delete Tandemmaster
A `DELETE` request is used to delete a tandemmaster.

operation::tandemmaster/delete-tandemmaster[snippets='http-request,path-parameters,http-response,response-fields']


== Assign Tandemmaster to jumpdays
A `PATCH` request is used to assign a tandemmaster to jumpdays.

operation::tandemmaster/assign-tandemmaster[snippets='http-request,path-parameters,request-fields,http-response,response-fields']


== Assign Tandemmaster to jumpdays (self-assign)
A `PATCH` request is used for a tandemmaster to assign himself to jumpdays.

operation::tandemmaster/self-assign-tandemmaster[snippets='http-request,path-parameters,request-fields,http-response,response-fields']
