language: java
jdk:
  - openjdk11
addons:
  sonarcloud:
    organization: "skyyaga-github"
    token:
      secure: "Z/7abitERhIeneAW7DsbL7gIWTFkuxExVCF2mS3bVKEa1yWPIw0pXvf9E2Mp6eaHSzFePq3/2JsP3rGDBLCgn1ABVhZLLH6dINqVHCClOLrzgWOpJibUhW6VDzl7QyeljV2P8x1CmMSOwH8Pio+eRZ//HT/hrbUbUceUFvCepml9yybUOrhGs52N4jxodzHJle8KbDSfOt5nruAKPbUjwskquNLDx726xygv1/s3bbn7Bc4QLTYIbzt0YMzLcrukXe5ao5YzPREHkTV3mkqLIvypCvvQTPR//GeDmFqbrQ0JGmSXMh5M5HNlG6xDVKQIF3E+suxd8n0eyInu9pfokQqLgQl86jY4sjJIPOrd7Yi5WG9Ng4Y2wUVAwNQ77vx3GS74bo8Cgk8FbnmYAnRvDPAiTv0MScYUtJjon2DOu5WbktOWVrXYUU4FnyRQqN8KH5rN5F3L+dERcEzLR/dzlUMQgJ+L0/FMo8WHyOjLaqD66ixQIOtpZGpDqKkqYOY6IWxV1TlUnAA80x3HPD9wBrXDnEy0imYG556PRdBwvXKval55dBCKqS5vUYi36dfH7CoBvAg+L33chsGbOiqznaZfVic4kv4jp79mXPZJ01kpGDdy7bIBsRbha4/zU6JjZ5AeMYsnwmB3380+JGQoeuK9uOcIF0FeHzN2hfOPpb4="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=in.skdv:skdvin-api
deploy:
  provider: heroku
  api_key:
    secure: km5nOCIiE4KmPurqSkuN3y2akL5sgixttwY0hz4PBxcXFHmbZrZb9nbVTkS0mDHxa9WvwrR3mUV+dhp9FjHrsnFSWrn0qWctIRyiUgleCSi7mZkGvXsDhNnE1vKblCZqjewRoNlS7lsT/kqHPPs0rzGLtfjoEzaQN0qsGVsqFT1+uol6TMoAjfZezoMYPs4U29Ieer+MvuyqsRrqQE6Doww399g8UxtiCwPbt3jxXpBoxYhhRGaeZ1/PHangjKZUGRqVPPQ42ZWDHew7qpwN965yILETJDKFtUfyIAiiFqvEt2l8DcpYgNJ1J3sLezf3kElidRx1RZnGiK4TPTLcV109s73iBBcex20ZqyrerQoNXNNQyc4DqUsUUIk3hqSpscEDLegvIfdWaHyWcTjpGwiF8ArDWSKHSKHSM1eRORw7WzyhneCUbBuSuASLgbs0Ng0JL7roWZTTOxJKwN91g1St6xfTMnkOx/As6HJyTQxiNJt2sC8vR0iXHE9h0Za9pfo1jIG6xlbigKF7n8fB/lQfPtlBW+AwX8bCaXnVq9Rz8FBWEno1/KU0FAH1DMAtOAz5S+spNDHZ4Yklr2HNmpup7b4PAqJ6E5CYjsCl6uRscHjC2eSfjM8BrTloe6a4WtnWQ8noctJ1uKel0gPpIjO4GDBPvj7eVVBIFVmoqHM=
  app:
    develop: skdvin-api-acc
  on: develop
