language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "skyyaga-github"
    token:
      secure: "Z/7abitERhIeneAW7DsbL7gIWTFkuxExVCF2mS3bVKEa1yWPIw0pXvf9E2Mp6eaHSzFePq3/2JsP3rGDBLCgn1ABVhZLLH6dINqVHCClOLrzgWOpJibUhW6VDzl7QyeljV2P8x1CmMSOwH8Pio+eRZ//HT/hrbUbUceUFvCepml9yybUOrhGs52N4jxodzHJle8KbDSfOt5nruAKPbUjwskquNLDx726xygv1/s3bbn7Bc4QLTYIbzt0YMzLcrukXe5ao5YzPREHkTV3mkqLIvypCvvQTPR//GeDmFqbrQ0JGmSXMh5M5HNlG6xDVKQIF3E+suxd8n0eyInu9pfokQqLgQl86jY4sjJIPOrd7Yi5WG9Ng4Y2wUVAwNQ77vx3GS74bo8Cgk8FbnmYAnRvDPAiTv0MScYUtJjon2DOu5WbktOWVrXYUU4FnyRQqN8KH5rN5F3L+dERcEzLR/dzlUMQgJ+L0/FMo8WHyOjLaqD66ixQIOtpZGpDqKkqYOY6IWxV1TlUnAA80x3HPD9wBrXDnEy0imYG556PRdBwvXKval55dBCKqS5vUYi36dfH7CoBvAg+L33chsGbOiqznaZfVic4kv4jp79mXPZJ01kpGDdy7bIBsRbha4/zU6JjZ5AeMYsnwmB3380+JGQoeuK9uOcIF0FeHzN2hfOPpb4="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
deploy:
  provider: heroku
  api_key:
    secure: fBxxoxcXPZjeEEyTS0MxRG6PmMuppL3wmfe2xIr7WWHBje4g2Fqze2JaiiXsNmKVi7BAITrKsGFZcjxBFswcvcs4WcrWf3/F0w4NWYG3RQ6H3tRvsSYVEp0KmusinDGU4gVnrNKqBHE8JWTstZsYPZvDfktTDZF4EATxvm4T0m0YoR+jcyDAuupUw19HsCpkAYzWjrZpgP2dQZz62m4sdMRBxePdv+ZGTWtJfQ8Ktl/pZ2o1KT+8g7aBWLo/UECPrlhWP0lsZ9S0wUIcfigy3G2B4CwWY3I5Hn6x6HwWW/JrhWbIEx7NWweyt+hTsnnE/BGHg86QkeJoUcLibEUABO/tXLg+g+jDxQ83Y03RNt8QV4wCMEIwQMe+xk/K8FRKef9plNgOSTj1uoXVtwRk3ZpVlyCayz3ZrU4RJ3BjUrmpMBrFPZzFUHVeJgOXkLjP3YoyyhQ3121sfwqKQo2kAQn07Cfco99/JVUP1NVyGq9LK5vcMiAY8iupiZRmVhbsHO/m8FILFCGOtnEhq1Y12+g7wHFjXUTzkemPVwUOHNA+/YjMIEwXe54vpIopmQsHK7yn0cZvdz5j4ONLA3gYU2k7ONZ9aLojvTcvOTcEV2udJsuVvilbuiQtiTB7FblFEQtyAdfXo1iPdAJ5KsPiz8YEezODXVJ8DRiCZOc1SG8=
  on: feature/heroku