logging:
  level:
    org.springframework.security: INFO
    com.auth0: INFO

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER:}
  data:
    mongodb:
      uri: ${DB_URI:mongodb://localhost/test}
      auto-index-creation: true
  mail:
    default-encoding: UTF-8
    host: ${MAIL_HOST:}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  jackson:
    serialization:
      write-dates-as-timestamps: false

auth0:
  audience: ${AUTH0_AUDIENCE:}
  management:
    domain: ${AUTH0_MANAGEMENT_DOMAIN:}
    client-id: ${AUTH0_MANAGEMENT_CLIENT_ID:}
    client-secret: ${AUTH0_MANAGEMENT_CLIENT_SECRET:}
skdvin:
  timezone: Europe/Paris
  baseurl: ${SKDVIN_BASEURL:}
  from: ${SKDVIN_FROM:}
  cors:
    enabled: ${SKDVIN_CORS_ENABLED:false}

sentry:
  traces-sample-rate: 0.3

springdoc:
  api-docs:
    path: /docs/api-docs
  swagger-ui:
    path: /docs/swagger-ui.html
    docExpansion: none
    tagsSorter: alpha

mongock:
  migration-scan-package:
    - in.skdv.skdvinbackend.migration