spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost/test}
  mail:
    default-encoding: UTF-8
    host:
    username:
    password:
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

skdvin:
  baseurl:
  from: