spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost/test}
  mail:
    default-encoding: UTF-8
    host: ${MAIL_HOST:}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  jackson:
    serialization:
      write-dates-as-timestamps: false

skdvin:
  baseurl: ${SKDVIN_BASEURL:}
  from: ${SKDVIN_FROM:}