== Videoflyer
API Endpoint to manage Videoflyers


=== Create/Add Videoflyer
A `POST` request is used to add a new videoflyer.

operation::videoflyer/create-videoflyer[snippets='http-request,request-fields,http-response,response-fields']


=== Get all Videoflyers
A `GET` request is used to get all videoflyers.

operation::videoflyer/get-videoflyers[snippets='http-request,http-response,response-fields']


=== Get Videoflyer
A `GET` request is used to get one videoflyers.

operation::videoflyer/get-videoflyer[snippets='http-request,path-parameters,http-response,response-fields']


=== Get Me Videoflyer
A `GET` request is used by a videoflyer to get his own data

operation::videoflyer/get-me-videoflyer[snippets='http-request,http-response,response-fields']


=== Update Videoflyer
A `PUT` request is used to update a videoflyer.

operation::videoflyer/update-videoflyer[snippets='http-request,path-parameters,request-fields,http-response,response-fields']


=== Delete Videoflyer
A `DELETE` request is used to delete a videoflyer.

operation::videoflyer/delete-videoflyer[snippets='http-request,path-parameters,http-response,response-fields']


=== Assign Videoflyer to jumpdays
A `PATCH` request is used to assign a videoflyer to jumpdays.

operation::videoflyer/assign-videoflyer[snippets='http-request,path-parameters,request-fields,http-response,response-fields']


=== Assign Videoflyer to jumpdays (self-assign)
A `PATCH` request is used for a videoflyer to assign himself to jumpdays.

operation::videoflyer/self-assign-videoflyer[snippets='http-request,request-fields,http-response,response-fields']