package in.skdv.skdvinbackend.model.entity;

public enum EmailType {
    APPOINTMENT_VERIFICATION,
    APPOINTMENT_CONFIRMATION,
    APPOINTMENT_UNCONFIRMED_CANCELLATION,
    APPOINTMENT_UPDATED,
    APPOINTMENT_DELETED,
    APPOINTMENT_REMINDER
}
