version: "3.8"

services:
  mongo1:
    image: mongo:5.0
    container_name: mongo1
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--oplogSize", "128" ]
    volumes:
      - ./data/mongo-1:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rs0', members:[{_id:0, host:'mongo1:27017'}, {_id:1, host:'mongo2:27018'}, {_id:2, host:'mongo3:27019'}]}).ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
      interval: 10s
      start_period: 30s

  mongo2:
    image: mongo:5.0
    container_name: mongo2
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27018", "--oplogSize", "128" ]
    volumes:
      - ./data/mongo-2:/data/db
    ports:
      - 27018:27018

  mongo3:
    image: mongo:5.0
    container_name: mongo3
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27019", "--oplogSize", "128" ]
    volumes:
      - ./data/mongo-3:/data/db
    ports:
      - 27019:27019