name: Create a maven release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with SonarCloud Analysis
        run: mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=in.skdv:skdvin-api -Dsonar.organization=skyyaga-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Release
        uses: qcastel/github-actions-maven-release@67ea2db
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
        with:
          maven-args: "-DskipTests"
          ssh-private-key: ${{ secrets.RELEASE_BOT_SSH_PRIVATE_KEY }}
          git-release-bot-name: "skyYaga-bot"
          git-release-bot-email: "skyyaga-bot@yaga.eu"
          gpg-enabled: "true"
          gpg-key-id: ${{ secrets.RELEASE_BOT_GPG_KEY_ID }}
          gpg-key: ${{ secrets.RELEASE_BOT_GPG_KEY }}
          gpg-passphrase: ${{ secrets.RELEASE_BOT_GPG_PASSPHRASE }}

